/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.google.guava.guava)
    runtimeOnly(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

group = "com.kibo.pgar.lib"
version = "0.0.1"
description = "kibo-pgar-lib"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
