pluginManagement {
    plugins {
        kotlin("jvm") version "2.1.10"
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "kibo-pgar-lib"
include("src:main:java")
findProject(":src:main:java")?.name = "java"
